# vim: filetype=hyprlang
################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
# monitor=,preferred,auto,auto
# monitor=,preferred,auto,1.0667
monitor=eDP-1,preferred,auto,1
monitor=DP-1,preferred,auto,1,mirror,eDP-1
