# -------------------------------------------------------------------
# ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██╗      █████╗ ███╗   ██╗██████╗
# ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██║     ██╔══██╗████╗  ██║██╔══██╗
# ███████║ ╚████╔╝ ██████╔╝██████╔╝██║     ███████║██╔██╗ ██║██║  ██║
# ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██║     ██╔══██║██║╚██╗██║██║  ██║
# ██║  ██║   ██║   ██║     ██║  ██║███████╗██║  ██║██║ ╚████║██████╔╝
# ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝
# -------------------------------------------------------------------


##############
### COLORS ###
##############
source = ~/.config/hypr/mocha.conf


################
### MONITORS ###
################
source = ~/.config/hypr/configs/monitors.conf


###################
### MY PROGRAMS ###
###################
source = ~/.config/hypr/configs/programs.conf


#################
### AUTOSTART ###
#################
source = ~/.config/hypr/configs/autostart.conf


#############################
### ENVIRONMENT VARIABLES ###
#############################
source = ~/.config/hypr/configs/environment.conf


#####################
### LOOK AND FEEL ###
#####################
source = ~/.config/hypr/configs/appearance.conf


##################
### ANIMATIONS ###
##################
source = ~/.config/hypr/configs/animation.conf


###################
### WINDOWRULES ###
###################
source = ~/.config/hypr/configs/windowrule.conf


##############
### LAYOUT ###
##############
source = ~/.config/hypr/configs/layout.conf


##############
### LAYOUT ###
##############
source = ~/.config/hypr/configs/misc.conf


#############
### INPUT ###
#############
source = ~/.config/hypr/configs/input.conf


###################
### KEYBINDINGS ###
###################
source = ~/.config/hypr/configs/keybinding.conf


##############################
### WINDOWS AND WORKSPACES ###
##############################
source = ~/.config/hypr/configs/workspacerule.conf


