# vim: filetype=hyprlang
###################
### WINDOWRULES ###
###################
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
#workspace = 3, layout:master:orientation:top
windowrule {
  name = windowrule-1
  border_size = 0
  rounding = 0
  match:float = 0
  match:workspace = w[tv1]
}

windowrule {
  name = windowrule-2
  border_size = 0
  rounding = 0
  match:float = 0
  match:workspace = f[1]
}

# seperate rule for red in fullscreen (kind of pointless)
windowrule {
  name = windowrule-3
  border_color = rgb(FF0000) rgb(880808)
  match:fullscreen = 1
}

#windowrule = workspace 3 silent, class:^(.*firefox.*)$, title:^(.*WaniKani.*)$  # this did not work
windowrule {
  name = windowrule-4
  workspace = 3
  tile = on
  match:class = ^(.*brave.*)$
  match:title = ^(.*takoboto.*)$
}

windowrule {
  name = windowrule-5
  workspace = 3
  tile = on
  match:class = ^(.*brave.*)$
  match:title = ^(.*wanikani.*)$
}


#windowrulev2 = size 50% 100%, position 0 0, tile, noanim, class:^(your_class_name)$
#windowrulev2 = size 30% 100%, position 0 0, tile, noanim, class:^(.*brave.*)$,title:^(.*takoboto.*)$
#windowrulev2 = size 40% 100%, position 0 0, tile, noanim, class:^(.*brave.*)$,title:^(.*wanikani.*)$
# create rules music player
windowrule {
  name = windowrule-6
  float = on
  center = on
  size = 1200 800
  match:class = ^(musicplayer)$
  match:title = ^(kitty)$
}

# create rules for neomutt email in html
windowrule {
  name = windowrule-7
  float = on
  center = on
  size = 1200 1000
  match:class = ^(.*brave.*)$
  match:title = ^(.*neomutt.*)$
}

# create rules for floating kitty for quick things
windowrule {
  name = windowrule-8
  float = on
  center = on
  size = 1200 800
  match:class = ^(popup)$
  match:title = ^(kitty)$
}

# create rules for window 8 (music player)
windowrule {
  name = windowrule-9
  pseudo = on
  match:class = ^(wsmp)$
  match:title = ^(kitty)$
}


