# vim: filetype=hyprlang
###################
### WINDOWRULES ###
###################
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
windowrule = rounding 0, floating:0, onworkspace:w[tv1]
windowrule = bordersize 0, floating:0, onworkspace:f[1]
windowrule = rounding 0, floating:0, onworkspace:f[1]
# seperate rule for red in fullscreen (kind of pointless)
windowrule = bordercolor rgb(FF0000) rgb(880808), fullscreen:1
#windowrule = workspace 3 silent, class:^(.*firefox.*)$, title:^(.*WaniKani.*)$  # this did not work
windowrule = tile,class:^(Brave-browser)$,title:^(.*wanikani.*)$
# create rules music player
windowrulev2 = float,class:^(musicplayer)$,title:^(kitty)$
windowrulev2 = center,class:^(musicplayer)$,title:^(kitty)$
windowrulev2 = size 1200 800,class:^(musicplayer)$,title:^(kitty)$
# create rules for neomutt email in html
windowrulev2 = float,class:^(Brave-browser)$,title:^(.*neomutt.*)$
windowrulev2 = center,class:^(Brave-browser)$,title:^(.*neomutt.*)$
windowrulev2 = size 1200 1000,class:^(Brave-browser)$,title:^(.*neomutt.*)$
# create rules for floating kitty for quick things
windowrulev2 = float,class:^(popup)$,title:^(kitty)$
windowrulev2 = center,class:^(popup)$,title:^(kitty)$
windowrulev2 = size 1200 800,class:^(popup)$,title:^(kitty)$
# create rules for window 8 (music player)
windowrulev2 = pseudo,class:^(wsmp)$,title:^(kitty)$
